# Generated by Django 3.1 on 2022-12-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orederproduct',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
