# Generated by Django 3.1 on 2022-12-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20221220_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orederproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orederproduct',
            name='size',
        ),
    ]
