# Generated by Django 3.1 on 2022-12-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('orders', '0003_auto_20221222_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orederproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orederproduct',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
