# Generated by Django 3.1 on 2022-12-22 12:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_variation'),
        ('orders', '0004_auto_20221222_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederProduct',
            new_name='OrderProduct',
        ),
    ]
